name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Generate
        run: |
          mkdir build
          pushd build
          cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles" ..
          popd
        shell: bash

      - name: Test
        run: |
          pushd build
          cmake --build . --target colette_test
          ./colette_test
          popd
        shell: bash

      - name: Pack
        run: |
          pushd build
          cmake --build . --target package
          popd
        shell: bash
