name: Go Test

on: [push, pull_request]

jobs:
  gotest:
    name: Go Test

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Go Mod Download
        run: |
          go mod download
        shell: bash

      - name: Test
        run: |
          go test -v
        shell: bash
